AUDIO_ENABLE = yes
MUSIC_ENABLE = no

DYNAMIC_MACRO_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = no
AUTO_SHIFT_ENABLE = yes

DYNAMIC_TAPPING_TERM_ENABLE = yes

TRI_LAYER_ENABLE = yes

#HAPTIC FEEBACK
HAPTIC_ENABLE = no

#PER KEY RGB
RGB_MATRIX_ENABLE = no

SRC += features/achordion.c
