AUDIO_ENABLE = yes
MUSIC_ENABLE = no

DYNAMIC_MACRO_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE = yes
AUTO_SHIFT_ENABLE = no

#HAPTIC FEEBACK
HAPTIC_ENABLE = no

#PER KEY RGB
RGB_MATRIX_ENABLE = no

SRC += features/achordion.c
